export type CentralDirByteMapType = {
  SIZE: number,
  SIGNATURE: number,
  VERSION_MADE: number,
  VERSION_EXTRACT: number,
  FLAGS: number,
  METHOD: number,
  TIME: number,
  DATE: number,
  CRC_32: number,
  COMPRESSED_SIZE: number,
  DECOMPRESSED_SIZE: number,
  FILENAME_LENGTH: number,
  EXTRA_FIELD: number,
  COMMENT_LENGTH: number,
  DISK_START: number,
  INTERNAL_ATTRIBUTES: number,
  EXTERNAL_ATTRIBUTES: number,
  OFFSET: number
}
